### 01-01 What is ML?

Features + Target -> ML -> Model

Then, Features + Model -> Predictions

### 01-02 ML vs. Rules

Converting to numbers

Predictions as probability

### 01-03 Supervised ML

Supervised ML:
g(X) ≈ y

Regression, Binary Classification, Multiclass Classification, Ranking

### 01-04 CRISP-DM

![CRISP-DM](crisp-dm.png)

### 01-05 Model Selection

60% Training <br>
20% Validation <br>

-- Select best model --<br>
-- Train on both train and val --

20% Testing <br><br>


Process:
1. Split
2. Train
3. Val
4. Select the best
5. Test
6. Check

### 01-07 Numpy

In [1]:
import numpy as np

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [7]:
list = [1, 2, 3, 4, 5]

np.array(list)

array([1, 2, 3, 4, 5])

In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
# 1st number to include, 2nd number to include, number of samples
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

#### Multi-dimensional arrays

In [12]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [17]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
n[0, 1]

np.int64(2)

In [19]:
n[2]

array([7, 8, 9])

In [20]:
n[:, 1]

array([2, 5, 8])

In [21]:
n[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### Random arrays

In [26]:
np.random.seed(42)
np.random.rand(5, 2)

array([[0.37454012, 0.95071431],
       [0.73199394, 0.59865848],
       [0.15601864, 0.15599452],
       [0.05808361, 0.86617615],
       [0.60111501, 0.70807258]])

In [27]:
np.random.seed(42)
np.random.randn(5,2)

array([[ 0.49671415, -0.1382643 ],
       [ 0.64768854,  1.52302986],
       [-0.23415337, -0.23413696],
       [ 1.57921282,  0.76743473],
       [-0.46947439,  0.54256004]])

In [28]:
np.random.seed(42)
np.random.randint(low=0, high=10, size=(5,2))

array([[6, 3],
       [7, 4],
       [6, 9],
       [2, 6],
       [7, 4]])

#### Element-wise operations

In [29]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [30]:
a + 1

array([1, 2, 3, 4, 5])

In [37]:
b =(10 + (a * 2)) ** 2 / 100

In [38]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

#### Comparison operations

In [34]:
a

array([0, 1, 2, 3, 4])

In [35]:
a >= 2

array([False, False,  True,  True,  True])

In [39]:
a >= b

array([False, False,  True,  True,  True])

In [40]:
a[a >= b]

array([2, 3, 4])

#### Summarising operations

In [41]:
a.min()

np.int64(0)

In [42]:
a.max()

np.int64(4)

In [43]:
a.sum()

np.int64(10)

In [44]:
a.mean()

np.float64(2.0)

In [45]:
a.std()

np.float64(1.4142135623730951)

In [46]:
n.sum()

np.int64(45)

### 01-08 Linear algebra

In [48]:
u = np.array([2, 4, 5 ,6])
u

array([2, 4, 5, 6])

In [49]:
v = np.array([1, 0, 0, 2])
v

array([1, 0, 0, 2])

In [50]:
u + v

array([3, 4, 5, 8])

In [51]:
# Vector-vector multiplication (dot product or inner product)

def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]
    result = 0.0

    for i in range(n):
        result += u[i] * v[i]

    return result

In [52]:
vector_vector_multiplication(u, v)

np.float64(14.0)

In [53]:
u.dot(v)

np.int64(14)

In [57]:
# Matrix-vector multiplication

def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]

    num_rows = U.shape[0]
    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)

    return result

In [56]:
# Capital letter to denote matrix

U = np.array(
    [
        [2, 4, 5, 6],
        [1, 2, 1, 2],
        [3, 1, 2, 1]    
    ]
)

U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [58]:
matrix_vector_multiplication(U, v)

array([14.,  5.,  5.])

In [59]:
U.dot(v)

array([14,  5,  5])

In [63]:
# Matrix-matrix multiplication

def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]

    num_rows = U.shape[0]
    num_cols = V.shape[1]   
    result = np.zeros((num_rows, num_cols))

    for i in range(num_cols):
        # Get the i-th column of V
        Vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, Vi)
        result[:, i] = Uvi

    return result

In [62]:
V = np.array(
    [
        [1, 1, 2],
        [0, 0.5, 1],
        [0, 2, 1],
        [2, 1, 0]
    ]
)

V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [64]:
matrix_matrix_multiplication(U, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [65]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

#### Identity matrix

In [67]:
I = np.eye(3)

I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [68]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [69]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [72]:
Vs = V[[0, 1, 2]]

Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [74]:
Vs_inv = np.linalg.inv(Vs)

Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [75]:
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 01-09 Pandas

In [76]:
import pandas as pd

#### Dataframe

In [87]:
data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia', 2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]

columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders', 
    'Transmission Type', 'Vehicle Style', 'MSRP'
]

In [81]:
df = pd.DataFrame(data)

df

         0         1     2      3  4          5            6      7
0   Nissan    Stanza  1991  138.0  4     MANUAL        sedan   2000
1  Hyundai    Sonata  2017    NaN  4  AUTOMATIC        Sedan  27150
2    Lotus     Elise  2010  218.0  4     MANUAL  convertible  54990
3      GMC    Acadia  2017  194.0  4  AUTOMATIC      4dr SUV  34450
4   Nissan  Frontier  2017  261.0  6     MANUAL       Pickup  32340

In [88]:
df = pd.DataFrame(data, columns=columns)

df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [82]:
data = [
    {
        'col_a': 1,
        'col_b': 2,
        'col_c': 3
    },
    {  
        'col_a': 11,
        'col_b': 22,
        'col_c': 33
    }
]

pd.DataFrame(data)

   col_a  col_b  col_c
0      1      2      3
1     11     22     33

In [89]:
df.head(n=2)

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150

#### Series

In [91]:
df.Make

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: object

In [92]:
df["Engine HP"]

0    138.0
1      NaN
2    218.0
3    194.0
4    261.0
Name: Engine HP, dtype: float64

In [93]:
df[["Make", "Model", "MSRP"]]

      Make     Model   MSRP
0   Nissan    Stanza   2000
1  Hyundai    Sonata  27150
2    Lotus     Elise  54990
3      GMC    Acadia  34450
4   Nissan  Frontier  32340

In [94]:
df["id"] = [1, 2, 3, 4, 5]

df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle Style,MSRP,id
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,1
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,2
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,3
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,4
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,5

In [95]:
del df['id']

df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

#### Index

In [96]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [97]:
df.Make

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: object

In [98]:
df.loc[1]

Make                   Hyundai
Model                   Sonata
Year                      2017
Engine HP                  NaN
Engine Cylinders             4
Transmission Type    AUTOMATIC
Vehicle Style            Sedan
MSRP                     27150
Name: 1, dtype: object

In [99]:
df.loc[[1, 2]]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle Style,MSRP
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990

In [100]:
df.index = ['a', 'b', 'c', 'd', 'e']

df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle Style,MSRP
a,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
b,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
c,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
d,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
e,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [101]:
df.loc[['b', 'c']]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle Style,MSRP
b,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
c,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990

In [102]:
df.iloc[1]

Make                   Hyundai
Model                   Sonata
Year                      2017
Engine HP                  NaN
Engine Cylinders             4
Transmission Type    AUTOMATIC
Vehicle Style            Sedan
MSRP                     27150
Name: b, dtype: object

In [103]:
df.iloc[[1, 2, 4]]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle Style,MSRP
b,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
c,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
e,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [105]:
df.reset_index()

,index,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle Style,MSRP
0,a,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,b,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,c,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,d,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,e,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [106]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle Style,MSRP
a,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
b,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
c,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
d,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
e,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [107]:
df.reset_index(drop=True)

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [108]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle Style,MSRP
a,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
b,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
c,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
d,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
e,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [109]:
df = df.reset_index(drop=True)

In [110]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

#### Element-wise operations

In [111]:
df["Engine HP"]

0    138.0
1      NaN
2    218.0
3    194.0
4    261.0
Name: Engine HP, dtype: float64

In [112]:
df["Engine HP"] / 100

0    1.38
1     NaN
2    2.18
3    1.94
4    2.61
Name: Engine HP, dtype: float64

In [114]:
df["Year"] >= 2015

0    False
1     True
2    False
3     True
4     True
Name: Year, dtype: bool

#### Filtering

In [115]:
df[df["Year"] >= 2015]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle Style,MSRP
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [117]:
df[(df["Make"] == "Nissan") & (df["Year"] >= 2015)]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle Style,MSRP
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

#### String operations

In [118]:
df["Vehicle Style"]

0          sedan
1          Sedan
2    convertible
3        4dr SUV
4         Pickup
Name: Vehicle Style, dtype: object

In [119]:
df["Vehicle Style"].str.lower()

0          sedan
1          sedan
2    convertible
3        4dr suv
4         pickup
Name: Vehicle Style, dtype: object

In [120]:
df["Vehicle Style"].str.replace(' ', '_')

0          sedan
1          Sedan
2    convertible
3        4dr_SUV
4         Pickup
Name: Vehicle Style, dtype: object

In [121]:
df["Vehicle Style"].str.replace(' ', '_').str.lower()

0          sedan
1          sedan
2    convertible
3        4dr_suv
4         pickup
Name: Vehicle Style, dtype: object

In [122]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [123]:
df["Vehicle Style"] = df["Vehicle Style"].str.replace(' ', '_').str.lower()

df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr_suv,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,pickup,32340

#### Summarising operations

In [124]:
df.MSRP

0     2000
1    27150
2    54990
3    34450
4    32340
Name: MSRP, dtype: int64

In [125]:
df.MSRP.min()

np.int64(2000)

In [126]:
df.MSRP.describe()

count        5.000000
mean     30186.000000
std      18985.044904
min       2000.000000
25%      27150.000000
50%      32340.000000
75%      34450.000000
max      54990.000000
Name: MSRP, dtype: float64

In [127]:
df.describe()

              Year  Engine HP  Engine Cylinders          MSRP
count     5.000000    4.00000          5.000000      5.000000
mean   2010.400000  202.75000          4.400000  30186.000000
std      11.260551   51.29896          0.894427  18985.044904
min    1991.000000  138.00000          4.000000   2000.000000
25%    2010.000000  180.00000          4.000000  27150.000000
50%    2017.000000  206.00000          4.000000  32340.000000
75%    2017.000000  228.75000          4.000000  34450.000000
max    2017.000000  261.00000          6.000000  54990.000000

In [128]:
df.describe().round(2)

          Year  Engine HP  Engine Cylinders      MSRP
count     5.00       4.00              5.00      5.00
mean   2010.40     202.75              4.40  30186.00
std      11.26      51.30              0.89  18985.04
min    1991.00     138.00              4.00   2000.00
25%    2010.00     180.00              4.00  27150.00
50%    2017.00     206.00              4.00  32340.00
75%    2017.00     228.75              4.00  34450.00
max    2017.00     261.00              6.00  54990.00

In [129]:
df.Make

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: object

In [130]:
df.Make.nunique()

4

In [131]:
df.nunique()

Make                 4
Model                5
Year                 3
Engine HP            4
Engine Cylinders     2
Transmission Type    2
Vehicle Style        4
MSRP                 5
dtype: int64

#### Missing values

In [132]:
df.isnull()

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle Style,MSRP
0,False,False,False,False,False,False,False,False
1,False,False,False,True,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False

In [133]:
df.isnull().sum()

Make                 0
Model                0
Year                 0
Engine HP            1
Engine Cylinders     0
Transmission Type    0
Vehicle Style        0
MSRP                 0
dtype: int64

#### Grouping

In [135]:
df.groupby("Transmission Type").MSRP.mean()

Transmission Type
AUTOMATIC    30800.000000
MANUAL       29776.666667
Name: MSRP, dtype: float64

#### Getting the NumPy arrays

In [136]:
df.MSRP.values

array([ 2000, 27150, 54990, 34450, 32340])

In [138]:
df.to_dict(orient="records")

[{'Make': 'Nissan',
  'Model': 'Stanza',
  'Year': 1991,
  'Engine HP': 138.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle Style': 'sedan',
  'MSRP': 2000},
 {'Make': 'Hyundai',
  'Model': 'Sonata',
  'Year': 2017,
  'Engine HP': nan,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle Style': 'sedan',
  'MSRP': 27150},
 {'Make': 'Lotus',
  'Model': 'Elise',
  'Year': 2010,
  'Engine HP': 218.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle Style': 'convertible',
  'MSRP': 54990},
 {'Make': 'GMC',
  'Model': 'Acadia',
  'Year': 2017,
  'Engine HP': 194.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle Style': '4dr_suv',
  'MSRP': 34450},
 {'Make': 'Nissan',
  'Model': 'Frontier',
  'Year': 2017,
  'Engine HP': 261.0,
  'Engine Cylinders': 6,
  'Transmission Type': 'MANUAL',
  'Vehicle Style': 'pickup',
  'MSRP': 32340}]